octokit/octokit.rb

lib/octokit/repository.rb
spec/octokit/repository_spec.rb

Raise an error when a Repository object is initialized with a string
that is not valid user/repo format.

Ensure Repository is valid when passed a string. Fixes #552

---

lib/octokit/error.rb
spec/octokit/client_spec.rb

Add a more explicit error when access to a repository is blocked.
See #563 for context.
Fixes #563

Raise RepositoryUnavailable when repository is blocked

---

spec/octokit/client/contents_spec.rb

The spec appears to fail currently in JRuby and Rubinius because of this missing require.

Adding require to spec to fix JRuby and Rubinius

---

lib/octokit/client/commit_comments.rb

I have problem when pull the commit_comments from github, the auto_paginate feature does not work. I checked in the commit_comments file and found out that, it used the method `get` instead of `paginate`.

Fix error not paginate with comment_comments. Auto paginate not working.

---

Gemfile

Apparently required for VCR now. This should fix failing CI.
/cc @zqzas

Add multi_json gem as test dependency

---

lib/octokit/client/hooks.rb

@pengwynn I have removed all the `ensure_org_hooks_api_media_type` and `warn_org_hooks_preview`.

Remove preview checks for org hooks

---

lib/octokit/client/hooks.rb

Because of theses defaults `edit_hook` is basically unusable. Imagine you want to add an event type:
```
client.edit_hook('my/repo', 'web', {}, add_events: ['status'])
```
This will actually mutate your hook to offer only the `push` event.
@pengwynn for review please.

#edit_hook should not have defaults

---

lib/octokit/client/organizations.rb

Found that organizations won't show up if there are organizations more
than 30. This will allow use of `auto_paginate` and fetch all
organizations.

Paginate fetch organizations

---

lib/octokit/connection.rb

@fotinakis rightly noticed that [some changes made to *client.rb*](https://github.com/octokit/octokit.rb/pull/582#issuecomment-110148506) were lost to the sands of time. This comes from 82ea118ec525b30a3d768c0cd2d04b4c9824dd62, which saw a bunch of shareable client connection methods moved out into their own module.
I went through the Git history and found two PRs that needed to be brought back in:
* https://github.com/octokit/octokit.rb/pull/583
* https://github.com/octokit/octokit.rb/pull/593
For an extra sanity check, it would be great if someone could verify that these are indeed the only client changes.
/cc @pengwynn for :eyes:

Incorporate connection changes that were made

---

lib/octokit/client/organizations.rb
spec/octokit/client/organizations_spec.rb

Adds Octokit support for a few methods that were overlooked in the [flurry of new Membership APIs][apis] last year.
/fyi @jakeboxer
[apis]: https://developer.github.com/changes/2014-09-16-finalizing-the-organization-and-team-membership-apis/

Implement /orgs/:org/memberships/:user methods

---

lib/octokit/client/repositories.rb
spec/octokit/client/repositories_spec.rb

Builds on #619, adding a failing test to be sure future :penguin: doesn't break this. 
/cc @tarebyte @kdaigle.
Closes #619.

Allow creating repo under org using organization ID instead of owner/name

---

lib/octokit/client/issues.rb
lib/octokit/client/milestones.rb

This applies to both issues and milestones where the default state is "open".
Although undocumented, the "all" option is confirmed to work.
See the API docs:
* https://developer.github.com/v3/issues/#parameters-1
* https://developer.github.com/v3/issues/milestones/#parameters

Update documentation to reflect the {state: "all"} option

---

README.md

Octokit uses Github releases to document changes in each release, rather than a changelog file. To avoid confusion, I've added a link to the releases page under the "Versioning" section.
This fixes #639

Added a link to the releases page in the readme

---

lib/octokit/client/repositories.rb
lib/octokit/error.rb
lib/octokit/repository.rb
spec/octokit/client/repositories_spec.rb
spec/octokit/repository_spec.rb

Hi,
I was using `Octokit.repository?` to check if a string was a valid github repository and I realised that it was returning `true` for repositories like `paths_with/more/than/one/slash`. I thought it could be a good idea to add a validation to the format of the repository and username.
This pull request:
- Validates repository format against `URI.regexp`
- Add `Octokit::InvalidRepository` error

Add validation of repository format

---

lib/octokit/repository.rb

Removes the unused named captures from the repository name-with-owner regex.

Simplify repo pattern

---

lib/octokit/error.rb
spec/octokit/client_spec.rb

A user with an unverified email address gets a 403 error when trying
to create a repository through the API. This can easily happen with a
brand new user account.
Some of the 403 errors (abuse, rate limits, etc) already have their
own error subclass to make it easier to work with -- this PR simply
adds a specific Octokit::UnverifiedEmail instead of relying on the
more generic Octokit::Forbidden error.

Add specific error when user has unverified email (for 403s)

---

lib/octokit/preview.rb

@pengwynn, @spraints, @jonmagic, _et al._ - this PR fixes the problem I documented in #627, namely that the message issued by the `Octokit::Preview.warn_preview` method is always warning about the "Migrations API", irrespective of the preview type passed into the `Octokit::Preview.ensure_api_media_type` method... small change, big difference! :smile:  thanks!
---
**before:**
```ruby
[1] pry(main)> Octokit::Preview.send(:module_function, :warn_preview)
=> Octokit::Preview
[2] pry(main)> Octokit::Preview.send(:module_function, :ensure_api_media_type)
=> Octokit::Preview
[3] pry(main)> Octokit::Preview.ensure_api_media_type(:migrations, {})
WARNING: The preview version of the Migrations API is not yet suitable for production use.
You can avoid this message by supplying an appropriate media …
```

Ensure the correct preview warning message is issued

---

lib/octokit/preview.rb

@pengwynn, @spraints, @jonmagic, _et al._ - this PR adds support for the "branch protection" preview API - code-named `loki-preview` - which was announced yesterday:
https://developer.github.com/changes/2015-11-11-protected-branches-api/
Use of `loki-preview` is left optional and up to the user, but - if used - retrieves the `protection` data of a branch, as illustrated by this example:
```shell
[1] pry(main)> ENV['OCTOKIT_ACCESS_TOKEN'].empty?
=> false
[2] pry(main)> pry Octokit::Client.new
[1] pry(#<Octokit::Client>)> ensure_api_media_type(:branch_protection, {})
WARNING: The preview version of the Migrations API is not yet suitable for production use.
You can avoid this message by supplying an appropriate media type in the 'Accept' request
header.
=> …
```

Support the "branch protection" preview API (`loki`)

---

lib/octokit/enterprise_admin_client/orgs.rb

Login and Admin need to be added to the post options to properly create an org.

Fix org creation to include login and admin.

---

lib/octokit/configurable.rb

This should close https://github.com/octokit/octokit.rb/issues/671.
/cc @pvdb It'd be great if you could grab this branch and confirm there's no warning, if possible.
/c @pengwynn

Set `management_console_*` ivars as only writeable

---

lib/octokit/client/authorizations.rb
spec/octokit/client/authorizations_spec.rb

Since that endpoint [no longer exists](https://developer.github.com/changes/2014-04-08-reset-api-tokens/), it probably shouldn't be listed in Octokit.

Deprecate "revoke all application authorizations" from Octokit

---

lib/octokit/client/issues.rb

The API accepts a comma separated list of labels, not an Array of Strings. There's a few other methods in this file that claim to accept `[Array<String>]` for the labels parameter. I haven't checked if those need to be updated as well.

Update docs for #list_issues :labels parameter

---

lib/octokit/client/deployments.rb

I was playing around with this neat API earlier and noticed that some really cool options 
were not documented on the Octokit side: 
- https://developer.github.com/v3/repos/deployments/#create-a-deployment-status
I can confirm that `target_url` and `description` work from testing them. The first 
adds a link to the status text in a PR pointing to the `target_url`. The second 
becomes the `title` attribute on that link.
This:
```ruby
client.create_deployment_status(url, "success", { target_url: "https://www.codeschool.com", description: "Things happened.!" })
```
Turns into that:

Docs for target_url & description status options

---

octokit.gemspec

This loosens sawyer addressable dependency which makes octokit less
strict on the addressable version.

Loosen sawyer dependency

---

lib/octokit/error.rb
spec/octokit/client_spec.rb

Those amazing folks at GitHub have started to support the `451` status code: https://developer.github.com/changes/2016-03-17-the-451-status-code-is-now-supported/
This PR modifies Octokit.rb to support this new code.
/cc Eagle-eyes @tarebyte

Implement recognition of the `451` status code

---

lib/octokit/client/source_import.rb

https://developer.github.com/v3/repos/source_imports gives:
> Whoops, looks like that page doesn't exist.
It seems the URL has changed to https://developer.github.com/v3/migration/source_imports.

Fix source_imports documentation URL

---

lib/octokit/preview.rb

Use `octokit_warn` instead of `warn` so we can silence the api preview messages.

Use octokit_warn instead of warn

---

lib/octokit/client/authorizations.rb
spec/helper.rb
spec/octokit/client/authorizations_spec.rb

`authorize_url` appends entries from `options` hash as query params *without* escaping values. This PR adds `CGI.escape` call to fix that, because `redirect_uri` and `scope` options probably have chars that should be encoded.

Escape options values in authorize_url

---

README.md

`shared_cache: false` is needed to cache responses with the `Cache-Control: private` header.
Without `serializer: Marshal`, `Faraday::HttpCache` would warn as:
> Response could not be serialized: "\\xE3" from ASCII-8BIT to UTF-8. Try using Marshal to serialize

Update README.md to describe proper caching

---

octokit.gemspec

Bump gemspec Required Ruby Runtime Version >= 2.0.0 per offically supported versions #753

Require Ruby Runtime Version >= 2.0.0

---

lib/octokit/client/organizations.rb
lib/octokit/client/repositories.rb

I thought it would be useful to document this option.
If you regenerate the docs with this change, it'll look like:
Previously it looked like:

Update add_collaborator and add_team_repository docs to include permission option

---

lib/octokit/error.rb
spec/octokit/client_spec.rb

Octokit subclasses errors depending on the response status.
This is great because it allows consumers to handle specific
errors properly.
It is not great if you want to keep audit logs of responses from remote servers.
You could use the class name, and do some normalization. You could also
parse the message that Octokit provides, but that has some other issues:
1. You need to know all the possible error classes Octokit implements to
handle error responses.
2. Parsing string is not the best way to do this.
3. It becomes a bigger issue if you integrate with different
Git Hostings that use different libraries and handle errors in different
ways. Octokit::NotFound is not the same as Gitlab::NotFound (I just made
this one up).
Status codes are the canonical way to know what happened with
an …

Expose response statuses when Octokit raises an error.

---

.travis.yml
README.md

- Updates the travis configuration to run on MRI 2.3.
- Updates README to include 2.3 as a supported version.

Run CI for MRI 2.3

---

lib/octokit/client/gists.rb

Changing a Gist's visibility (`public` or `secret`) via the API is not supported, and not mentioned in the [Edit a gist](https://developer.github.com/v3/gists/#edit-a-gist) section of the [GitHub API documentation](https://developer.github.com/v3/). However in the [edit_gist](http://octokit.github.io/octokit.rb/Octokit/Client/Gists.html#edit_gist-instance_method) method of Octokit's documentation, `:public` option is described as if it were able to change a Gist's visibility:
> :public (Boolean) — Sets gist visibility
I tested this myself by using Octokit's `:public` option to try to change a Gist's visibility, however this does nothing. This is because the implementation of the API endpoint does not handle the `:public` option.
This PR removes the line from the Yard doc of the …

[ci skip] Remove option :public from gists.rb's doc

---

lib/octokit/enterprise_admin_client.rb
spec/octokit/enterprise_admin_client_spec.rb

I thought I was doing something wrong when `Octokit::EnterpriseAdminClient.new(:netrc => true)` didn't seem to work, but it wasn't implemented, [like it is](https://github.com/octokit/octokit.rb/blob/265de586860c2e108dc815d7e5609c622e5c8660/lib/octokit/client.rb#L112) for `Octokit::Client`.
This adds `.netrc` support to `Octokit::EnterpriseAdminClient`.
On `master`:
```
admin_client = Octokit::EnterpriseAdminClient.new(:netrc => true)
admin_client.login
=> nil
```
On this branch:
```
admin_client = Octokit::EnterpriseAdminClient.new(:netrc => true)
admin_client.login
=> "jdennes"
```

Add .netrc support to Octokit::EnterpriseAdminClient

---

lib/octokit/client/issues.rb
spec/octokit/client/issues_spec.rb

With the recent finalizing of the API endpoints to lock and unlock
issues, we should include that functionality in Octokit.rb. This patch
adds two methods to lock or unlock an issue. Because the corresponding
API endpoints return a 204 NO CONTENT on success, we just coerce the
response into a Boolean for the Octokit methods.
Side note: not entirely sure what to do to get VCR to work in this repo. I
wrote some corresponding specs but I'm waiting to see what CI says.

Add `Client.lock_issue` and `Client.unlock_issue`

---

lib/octokit/client/releases.rb

Calling `#upload_assets` on a file caused it to be opened using "r+b" which is read-write. This prevents `#upload_file` from working with assets that are read-only. Given the method does not attempt to modify the file, the correct open flag should be "rb".

#upload_assets should open files in read-only mode

---

lib/octokit/client/repositories.rb

WHY:
I was getting unexpected behavior from my program in a class that wraps
Octokit. After looking at the source code I realized it was because the
hash I was passing to Repositories#create_repo was being mutated inside
the method. I'm thinking it would be better to dupe the hash before
mutating it to avoid surprises to the user. I named the duped version `opts` so that it would be clear inside the method that this object is not the same as the one passed in.

Dupe the options hash in Repositories#create_repo

---

lib/octokit/client/deployments.rb
spec/octokit/client/deployments_spec.rb

This PR is to add support for getting a single deployment by id. Unfortunately, I'm not able to get my test to work because of a credential issue:
```
Failures:
1) Octokit::Client::Deployments.deployment gets single deployment
Failure/Error: deployment = @client.deployment(@test_repo, 137)
Octokit::Unauthorized:
GET https://api.github.com/repos/api-padawan/api-sandbox?auto_init=true: 401 - Bad credentials // See: https://developer.github.com/v3
```
Let me know how I can resolve this, and I'll make the necessary changes.

adding support for getting a single deployment by id

---

lib/octokit/repository.rb

Try to avoid the warning "URI.regexp is obsolete" by using one of the specific regular expressions made available to the `URI` module.
Benefit: much less chatty output. 
Example: [this test output](https://travis-ci.org/skywinder/github-changelog-generator/jobs/165365731)

Repository: Avoid obsolete warning using URI::ABS_URI

---

lib/octokit/client/stats.rb
spec/octokit/client/stats_spec.rb

Currently any method from `Octokit::Client::Stats` may return an `Array` of `Sawyer::Resource` objects, `nil` or an empty `Sawyer::Resource`. That's because returning `data` upon timeout will return the data of the 202 response, which is an empty JSON object.
The documentation for the private `get_stats` method doesn't mention returning a single `Sawyer::Resource` so I assumed it's not a specified behavior. Additionally when using `retry_timeout: nil`, it returns nil when it gets a 202.
This changes `get_stats` to return `nil` in this case too.

Return nil on timeout fetching stats

---

lib/octokit/client/pages.rb

@joeyw This addresses my comment from https://github.com/octokit/octokit.rb/pull/815/files#r84807489.
This is currently broken in v4.4.0.

Remove requested 'Accept' header from GET /repos/o/r/pages

---

octokit.gemspec

Following on from loosing the addressable dependency in sawyer https://github.com/lostisland/sawyer/pull/46
🐰

Loosen sawyer dependency to allow 0.8.0

---

lib/ext/sawyer/relation.rb

My app has a `::Patch` class. This PR fixes name collision problem.

Avoid polluting global namespace

---

lib/octokit/client/organizations.rb

Passing "since" did not work when calling "all_organizations" as it was
not passed to "paginate".

Fix passing options to all_organizations

---

spec/octokit/rate_limit_spec.rb

The specs on `Octokit::RateLimit` define a subject that is never used. Also did fix for typo on `resonse_headers`

Removing unused rspec.subject and fixing typos on a variable name

---

lib/octokit/client/projects.rb

Several of the examples for the projects endpoints showed additional parameters that are not correct, probably copy / paste errors.

Correct project documentation examples

---

Gemfile
lib/octokit/client/authorizations.rb
spec/octokit/client/authorizations_spec.rb

Fixes #831, this change switches to a relative path so that URLs are built correctly on Enterprise (and lab) hosts.
/cc @tarebyte @GordonDiggs

Fix application requests for non dotcom hosts

---

lib/octokit/connection.rb

Otherwise, you can't do this:
```ruby
headers = {accept: 'application/vnd.github.drax-preview+json'}
response = Octokit.repository_license_contents('octokit/octokit.rb', options)
response = Octokit.repository_license_contents('octokit/octokit.py', options)
```

Don't mutate the options variable passed to API calls

---

.travis.yml
lib/octokit/client/labels.rb
lib/octokit/client/rate_limit.rb
lib/octokit/client/search.rb
lib/octokit/client/source_import.rb
lib/octokit/default.rb
lib/octokit/gist.rb
lib/octokit/middleware/follow_redirects.rb
lib/octokit/rate_limit.rb
spec/octokit/client/rate_limit_spec.rb
spec/octokit/client/search_spec.rb
spec/octokit/enterprise_admin_client/admin_stats_spec.rb
spec/octokit/enterprise_admin_client/license_spec.rb
spec/octokit/gist_spec.rb

Fix deprecated `constant ::Fixnum`.
Ruby 2.4 unifies Fixnum and Bignum into Integer: https://bugs.ruby-lang.org/issues/12005
When I ran the following code in Ruby 2.4.0, `warning: constant ::Fixnum is deprecated` was displayed.
* ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin14], MacOSX 10.10.5
```
irb(main):001:0> Octokit::Gist.from_url('https://api.github.com/gists/7e09512c9d4477d474e4')
=> /Users/aikyo/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/octokit-4.6.2/lib/octokit/gist.rb:18: warning: constant ::Fixnum is deprecated
#<Octokit::Gist:0x007ff611dd23b8 @id="gists/7e09512c9d4477d474e4">
```
This cause is that Fixnum is deprecated. So, I fixed it.
I confirmed this fixes work well on Ruby 2.4.0 and Ruby 2.3.2.
```
irb(main):001:0> …
```

Fix deprecated `constant ::Fixnum`

---

lib/octokit/client/organizations.rb
spec/octokit/client/organizations_spec.rb

Fixes the issue described by @jules2689 in https://github.com/octobox/octobox/pull/314#issuecomment-281495851.
This method uses the `Organization.path` instead of just hard coding `orgs` so that we can use the ID of an organization instead of just the login.

Use Organization.path for organization membership method

---

lib/octokit/authentication.rb
lib/octokit/client.rb
lib/octokit/configurable.rb
lib/octokit/connection.rb
lib/octokit/default.rb
spec/octokit/client_spec.rb

Support authenticating Octokit with JWT bearer tokens #812
```ruby
Octokit::Client.new(bearer_token: 'super_secret_token') =>
Authorization: Bearer super_secret_token
```

Support Bearer JWT authentication #812

---

lib/octokit/error.rb
spec/octokit/client_spec.rb

When using GitHub's Reviews via API, it seems that errors that are
returned are strings, rather than hashes.
For certain requests, we're seeing errors like:
```
undefined method `map' for "Position is invalid":String Did you mean? tap
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.6.2/lib/octokit/error.rb:142:in `block in response_error_summary'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.6.2/lib/octokit/error.rb:141:in `map'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.6.2/lib/octokit/error.rb:141:in `response_error_summary'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.6.2/lib/octokit/error.rb:156:in `build_error_message'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.6.2/lib/octokit/error.rb:39:in `initialize'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.6.2/lib/octokit/error.rb:33:in …
```

Handle PR Review errors

---

lib/octokit/preview.rb

Just a small fix related to the new *Integrations*.

Fix incorrect mimetype for integrations in PREVIEW_TYPES

---

lib/octokit/client/organizations.rb

the documentation previously linked to an anchor that didn't exist.
cc @gjtorikian or @tarebyte because i don't know who else to include because there's no maintainers list 😨 
❤️

Incorrect anchor link to add-create-membership

---

lib/octokit/error.rb
spec/octokit/client_spec.rb

Previously, the only way to get at these was with `error.instance_variable_get(:@response)`, which is grim.

Expose response_headers and response_body on error objects

---

lib/octokit/repository.rb
spec/octokit/repository_spec.rb

Note: Test cases for this PR is failed now. It will be fixed if #876 was merged.
Currently, an error message of `Octokit::Repository.new` is unkind.
For example:
```ruby
Octokit::Repository.new(nil) # => Octokit::InvalidRepository: Invalid Repository. Use user/repo format.
```
If an user want to pass an id(Integer), this message is wrong for the user. Because the user doesn't expect the `user/repo` format.
This change improves the error message.
So, this change makes debugging easier.

Make to understandable error message when `Octokit::Repository.new`is failed

---

lib/octokit/client/notifications.rb

As per the [https://developer.github.com/v3/activity/notifications/#mark-a-thread-as-read](https://developer.github.com/v3/activity/notifications/#mark-a-thread-as-read), this endpoint no longer recognises any options passed to it.
@andrew and I attempted to change a notification's unread status, via the optional argument, but this was not possible.

Delete docs for defunct options for marking thread as read

---

.travis.yml

Currently [Rubies 2.2 - 2.4 are currently supported](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/) in any capacity, so I removed non supported ruby versions from the test matrix.

Remove Ruby 2.0 and 2.1 from Travis CI Matrix

---

lib/octokit/client/repositories.rb

This documentation seems to be out of date as of our latest upgrade to Github Enterprise. 
Based on these docs (https://developer.github.com/enterprise/2.11/v3/repos/branches/#update-branch-protection) and local testing the required option is now called `enforce_admins`.
```
[Execute release_branch:create_and_push] Octokit::UnprocessableEntity: PUT https://git.musta.ch/api/v3/repos/airbnb/apps/branches/ios-release-17.41/protection: 422 - Invalid request.
"enforce_admins" wasn't supplied. // See: https://developer.github.com/enterprise/2.11/v3/repos/branches/#update-branch-protection
Stacktrace:
/mnt/TeamCity/agents/buildAgent/work/8e63ecc810b1f294/android/vendor/bundle/ruby/2.3.0/gems/octokit-4.7.0/lib/octokit/response/raise_error.rb:16:in `on_complete' …
```

Update required option for `protect_branch` method

---

README.md

`contents` example seems wrong on README. 
When I try the example it gives this error;
```ruby
client.contents(repo: "octokit/octokit.rb", :path => 'lib/octokit.rb')
Octokit::NotFound: GET https://api.github.com/contents/: 404 - Not Found // See: https://developer.github.com/v3
```
As documentation indicates it should take repo as first argument.
http://www.rubydoc.info/gems/octokit/Octokit/Client/Contents#contents-instance_method
Also documentation says `options` hash should include  `path` and `ref` but example still includes `query: { ref: 'some-other-branch' }`.  Example works as it is but it is kind of inconsistent with the documentation. I am not sure which one should be fixed documentation or example, so I didn't touch.

fixes contents method example on README [ci skip]

---

spec/octokit/client/apps_spec.rb
spec/octokit/client/issues_spec.rb
spec/octokit/client/marketplace_spec.rb
spec/octokit/client/organizations_spec.rb
spec/octokit/client/pages_spec.rb
spec/octokit/client/projects_spec.rb
spec/octokit/client/reactions_spec.rb
spec/octokit/client/repositories_spec.rb
spec/octokit/client/repository_invitations_spec.rb
spec/octokit/client/source_import_spec.rb
spec/octokit/client/traffic_spec.rb

This passes the preview header to any calls made from the specs in order to make the test run a bit less noisy.

Get rid of preview warnings when running the tests

---

lib/octokit/client/apps.rb
spec/octokit/client/apps_spec.rb

This shows and fixes the fact that the client doesn't work correctly for the app endpoints documented at https://developer.github.com/v3/apps/ when used in a GitHub Enterprise environment.
Without this change requests like `POST https://ghe.localhost/installations/:installation_id/access_tokens` are being made instead of `POST https://ghe.localhost/api/v3/installations/:installation_id/access_tokens`, for example.
I had to manually patch the client to work with Octokit.rb using these endpoints on a GitHub Enterprise install.
Seems similar to https://github.com/octokit/octokit.rb/issues/831 + https://github.com/octokit/octokit.rb/pull/851.

Fix apps client for GitHub Enterprise installs

---

RELEASE.md

This is nothing new or special, but it should provide a handy checklist for cutting new releases,
which in turn might cause us to do this more often.
The gap between the v4.7.0 and v4.8.0 releases was about 8 months, mostly because we had some
turnover in maintainers, and the new maintainers had never cut a release, so it loomed as a somewhat uncomfortable unknown.
Documenting this should make it easier for new maintainers to whip up a release when it makes sense to do so.
[View rendered checklist](https://github.com/octokit/octokit.rb/blob/kytrinyx/release-docs/RELEASE.md)
@pengwynn since you've probably done most of the releases until now, would you have 5 minutes to glance through this checklist and make sure I'm not missing anything?
/cc @bkeepers as unofficial cat-herder of the …

Document the steps necessary to cut a release

---

lib/octokit/client/pull_requests.rb

The `sort` and `direction` options had incorrect values. Update them to be consistent with the intent of the example.

Fix pull_requests_comments example documentation

---

.travis.yml

https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-2-9-released/
https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-3-6-released/
https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-4-3-released/

CI against Ruby 2.2.9, 2.3.6, 2.4.3

---

lib/octokit/client.rb
lib/octokit/configurable.rb
lib/octokit/connection.rb
lib/octokit/default.rb
spec/octokit/client_spec.rb

Be able to set an SSL verify mode on faraday

---

lib/octokit/client/releases.rb

The [edit_release](https://developer.github.com/v3/repos/releases/#edit-a-release) endpoint accepts a tag_name so that should be documented here.
Furthermore, when using the `update_release` method without specifying a tag_name, the tag in Github is overwritten. 
For example, my tag was "v4.0" and after calling `update_release` without a tag name it became "untagged-{commit-hash}".

Add tag_name to update_release documentation

---

lib/octokit/client/issues.rb

Responds to the issue I opened [here](https://github.com/octokit/octokit.rb/issues/1007).
The documentation for getting a single issue comment was incorrect.

Fixes documentation for getting single issue comment

---

lib/octokit/client/organizations.rb

No tests added because these "org" short-form aliases are not tested in the suite.

Add missing remove_org_membership alias

---

lib/octokit/client/labels.rb

Before:
Octokit.labels("octokit/octokit.rb", "V3 Addition")
Traceback (most recent call last):
7: from /usr/local/bin/irb:11:in `<main>'
6: from (irb):6
5: from /usr/local/lib/ruby/gems/2.5.0/gems/octokit-4.8.0/lib/octokit.rb:46:in `method_missing'
4: from /usr/local/lib/ruby/gems/2.5.0/gems/octokit-4.8.0/lib/octokit/client/labels.rb:19:in `labels'
3: from /usr/local/lib/ruby/gems/2.5.0/gems/octokit-4.8.0/lib/octokit/connection.rb:79:in `paginate'
2: from /usr/local/lib/ruby/gems/2.5.0/gems/octokit-4.8.0/lib/octokit/connection.rb:185:in `parse_query_and_convenience_headers'
1: from /usr/local/lib/ruby/gems/2.5.0/gems/octokit-4.8.0/lib/octokit/connection.rb:185:in `delete'
TypeError (no implicit conversion of Symbol into String)
After:
Octokit.label("octokit/octokit.rb", "V3 Addition")
=> …

Fix example call to Octokit.label

---

lib/octokit/client/reviews.rb

The use of `id` as a variable name here is a bit confusing - using `number` makes it more obvious what's going on.
Docs [here](https://developer.github.com/v3/pulls/review_requests/).

Document that PR review endpoints use PR number, not PR ID

---

lib/octokit/preview.rb

Marketplace is [out of preview](https://developer.github.com/changes/2018-05-22-marketplace-api/). 🎉

Remove preview warning for marketplace API

---

lib/octokit/default.rb

Currently, setting OCTOKIT_SSL_VERIFY_MODE causes Octokit to fail because environment variables are strings and ssl_verify_mode returns an integer:
```
06:05 $ export OCTOKIT_SSL_VERIFY_MODE=1
✔ ~/git/octokit.rb [master|✔] 
06:06 $ bundle exec irb
irb(main):002:0> client = Octokit::Client.new()
...
irb(main):003:0> client.user
Traceback (most recent call last):
16: from /home/chris/git/octokit.rb/.bundle/gems/faraday-0.15.1/lib/faraday/rack_builder.rb:143:in 
...
...
1: from /usr/share/ruby/net/http.rb:973:in `initialize'
TypeError (no implicit conversion of String into Integer)
```
The change in this PR returns the string as an integer.

Convert OCTOKIT_SSL_VERIFY_MODE environment variable to integer

---

README.md
lib/octokit/default.rb

Ref https://github.com/octokit/octokit.rb/issues/888
I think that is all the required changes to make everyone happy regarding intermittent Github 5xx error class errors that could be easily replayed.
🎩manually with the `Octokit::NotFound` error. 
Thoughts? I'm not super familiar with Octokit (it just work so I never had to look inside)

Faraday retry middleware

---

README.md

This is related to https://github.com/octokit/octokit.rb/issues/893.
The purpose of this PR is to update the README so it does not encourage developers to use methods directly on the Octokit module by updating example code to use Octokit client instances instead. Using methods directly on the Octokit module is not thread-safe (I've run into this firsthand), and @kytrinyx suggested that this ability would be deprecated. 
I also fixed a coding style inconsistency was bugging me where sometimes we had:
```ruby
client = Octokit::Client.new(:login => 'defunkt', :password => 'c0d3b4ssssss!')
```
and in other places:
```ruby
client = Octokit::Client.new \
:login    => 'defunkt',
:password => 'c0d3b4ssssss!'
```
I feel like the former is what we should be encouraging to new developers so I …

Updates README to use instance methods

---

lib/octokit/client/stats.rb
spec/octokit/client/stats_spec.rb

Fixes https://github.com/octokit/octokit.rb/issues/912
Closes https://github.com/octokit/octokit.rb/pull/994
Me, @srinjoym and @benemdon finished up @Kadaaran 's work from #994, fixing the timeout bug in the contributors endpoint.
GitHub returns a 204 when asking for statistics on empty repos. Previously, Octokit would continue to retry until the retry timeout was reached.
This PR just returns `[]` when a 204 is returned.
Also wrote a few tests showing we don't retry when a 204 is returned, and that octokit returns `[]` when GitHub returns a 204.
cc @tarebyte @kytrinyx for review

Fix contributors endpoint for empty repos

---

lib/octokit/client/statuses.rb

Allowing auto_paginate option to work when retrieving git status checks. Currently auto pagination is already in use for retrieving pull requests, commits etc. but not for statuses.
Closes https://github.com/octokit/octokit.rb/issues/1031

Use auto pagination when retrieving statuses

---

lib/octokit/client/authorizations.rb

Problem
===
`authorize_url` method call `options.dup`, but it does not use the duplicated option. So the method breaks the option that is received as an argument.
I notice this problem with `ruby -w`. For example:
```bash
$ ruby -w -roctokit -e '()'
/path/to/gems/2.6.0/gems/octokit-4.9.0/lib/octokit/client/authorizations.rb:230: warning: assigned but unused variable - opts
```
Solution
===
Use duplicated options.

Duplicate option to prevent to break argument

---

.travis.yml

This Pull Request add Ruby 2.5.1 to test matrix and update other existing Rubies to [latest stable](https://github.com/postmodern/ruby-versions/blob/master/ruby/stable.txt).

Test against Ruby 2.5.1

---

lib/octokit/client/marketplace.rb
spec/octokit/client/marketplace_spec.rb

This is a follow-up to https://github.com/octokit/octokit.rb/pull/1020
I didn't think that through entirely when I reviewed it. We need to remove the call to `ensure...` as well as the calls in the tests.

Remove marketplace preview warnings

---

lib/octokit/client/repository_invitations.rb
lib/octokit/preview.rb
spec/octokit/client/repository_invitations_spec.rb

The swamp-thing preview was graduated on July 2, 2018.

Remove preview warning for Repository Invitations API

---

spec/octokit/client/repositories_spec.rb

This avoids typos, and makes it easier to detect cleanup that needs to happen when previews are graduated.

Look preview header up in preview types hash

---

README.md

Follow up of 24673aaa3981c724540a1634fdfb7cbd7b6c3479

Add Ruby 2.5 to Supported Ruby Versions [ci skip]

---

README.md

By default, Octokit does not set timeouts on requests. Setting timeouts is important in order to avoid Ruby’s `Timeout` module, which can hose your server. This has happened in [Pull Reminders](https://github.com/marketplace/pull-reminders/) – see links below for more info. It took me a bit to figure out how to set timeouts in Octokit, so this pull request adds instructions to the README.
- [The Oldest Bug In Ruby - Why Rack::Timeout Might Hose your Server](https://www.schneems.com/2017/02/21/the-oldest-bug-in-ruby-why-racktimeout-might-hose-your-server/)
- [Timeout: Ruby's Most Dangerous API](https://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/)
- [The Ultimate Guide to Ruby Timeouts](https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts)

Adds timeout instructions to readme

---

lib/octokit/client.rb

Closes #1088
Enables configuration to include falsy values
You can manually verify by running `script/console` with the following code
```ruby
c = Octokit::Client.new(auto_paginate: false)
c.instance_variable_get(:@auto_paginate)
```

Support falsy values in configuration

---

lib/octokit/client/projects.rb

This allows the `auto_paginate` setting on the Client object to work with `org_projects` and prevents people from having to paginate manually even when using auto pagination.

Support auto pagination in org_projects

---

lib/octokit/client/repositories.rb

According to the GitHub API latest documentation, the `affiliation` option allows `outside`, `direct`, or `all`.
See <https://developer.github.com/v3/repos/collaborators/#list-collaborators>.

Update doc of `Repositories#collaborators` method

---

lib/octokit/error.rb
spec/octokit/client_spec.rb

I try adding the new exception class `Octokit::TooLargeContent`. Please give me any feedback. 🙏 
Fix #1104

Add `Octokit::TooLargeContent` for relevant 403 status

---

CONTRIBUTING.md

Hello! 
I was reading through the contributing docs, and noticed a bit that seems to want us to go back and write more tests (step 3), but actually says to go back to step 4, which is to run the tests.
Thanks!

Update reference to "add specs" step in CONTRIBUTING

---

lib/octokit/client/refs.rb

The example in the documentation for `update_branch` was calling `update_ref`:
This PR corrects the example to call `update_branch` instead.

Fix example in #update_branch documentation to call the correct method

---

.github/workflows/workflow.yml

A fix for the warning on [our CI builds](https://github.com/octokit/octokit.rb/pull/1138/checks?check_run_id=230322184#step:3:1):
```
##[warning]Input 'version' has been deprecated with message: The version property will not be supported after October 1, 2019. Use ruby-version instead
```
Note: support is dropping for it in about a week and a half.

Update deprecated `version` for `ruby-version`

---

lib/octokit/error.rb
spec/octokit/client_spec.rb

This adds a custom error class for `403` responses when the resource is SAML protected.
This makes error handling much easier 😄

Add SAML enforcement error to list of possible 403 reasons

---

.github/workflows/workflow.yml

This allows CI to run on PRs that are open against `master` and `4-stable`

Add 4-stable brach to CI config

---

README.md

Based on https://github.com/octokit/octokit.rb/issues/517, the docs are somewhat misleading because the pagination method only works for 1 additional page. Since that's a somewhat rare use-case, it would save some readers confusion to not have to face this bug

Update Pagination section of README to use client.get

---

README.md

> Based on https://github.com/octokit/octokit.rb/issues/517, the docs are somewhat misleading because the pagination method only works for 1 additional page. Since that's a somewhat rare use-case, it would save some readers confusion to not have to face this bug

[Backport] "Update Pagination section of README to use client.get"

---

.github/workflows/workflow.yml

This should fix the issue where folks who are opening PRs against the `4-stable` branch aren't being built.

[CI] Add 4-stable branch to CI config

---

lib/octokit/client/refs.rb

Previously the description of the `force` parameter was:
> A flag indicating one wants to force the update to make sure the update is a fast-forward update.
which is contradictory: a force update does *not* make sure the update is a fast-forward update -- rather, the opposite.
The docs also link to the official API docs for the update-a-reference endpoint:
https://developer.github.com/v3/git/refs/#update-a-reference
There, the description of the force parameter is:
> Indicates whether to force the update or to make sure the update is a fast-forward update
It's almost the same, but has the crucial "or" which was missing in the octokit documentation. So here, I've updated the octokit documentation to mirror the wording on the official API docs. Additionally, I've added an example of how to …

Clarify force vs fast-forward updates in #update_ref and #update_branch docs

---

lib/octokit/authentication.rb
lib/octokit/client/users.rb
lib/octokit/connection.rb
spec/octokit/client/users_spec.rb
spec/octokit/client_spec.rb

See https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
Users have started receiving emails that passing the `client_id` and `client_secret` as HTTP query parameters is now a deprecated form of authentication (ex https://github.com/octokit/octokit.rb/issues/1191).
This updates the Sawyer Agent so that we use `client_id` and `client_secret` as the login and password like basic authentication. We already do this as a special method in the client: https://github.com/octokit/octokit.rb/blob/0dfc8cfc1dd8e5d88656b35e589fe3c1579a6823/lib/octokit/client.rb#L152-L175

Remove the user of client_id and client_secret as query parameters

---

lib/octokit/authentication.rb
lib/octokit/client/users.rb
lib/octokit/connection.rb
spec/octokit/client/users_spec.rb
spec/octokit/client_spec.rb

This backports https://github.com/octokit/octokit.rb/pull/1192 to master

[Backport] Remove the user of client_id and client_secret as query parameters

---

lib/octokit/client/search.rb

This is the `4-stable` version of #1199
Minor change, but based on what I can tell, this should be the proper anchor tag:
https://developer.github.com/v3/search/#search-issues-and-pull-requests
v.s.
https://developer.github.com/v3/search/#search-issues
Which will default to the table of contents (not that a user wouldn't be able to figure it out from there).

Fix API search doc link

---

lib/octokit/authentication.rb

Documentation specifies that this method returns a boolean when it returns the `@client_secret` or nil.

Return a boolean for application_authenticated

---

.github/workflows/octokit.yml
README.md

It has been a few months since [Ruby 2.7 was released](https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/).
I think it's time we supported Ruby 2.7.
This change adds Ruby 2.7 to our CI workflow (also small refactorings).
In addition, this change fixes also the "Supported Ruby Versions" section in the README,
because this section refers to Travis CI that is no longer used and describes older Ruby versions (<= 2.4) that are not tested.
The gemspec sets `required_ruby_version = '>= 2.0.0'` and it probably should be fixed together.
But the gemspec change may break existing library users, so I don't it. Please give me more information about this if you have.
https://github.com/octokit/octokit.rb/blob/002cba873b676af014a5de8ab3d8ea65a30c6edd/octokit.gemspec#L19
```diff …
```

Support Ruby 2.7

---

lib/openapi_client_generator.rb

This PR is a reiteration of #1237 (and part of #1157). Instead of just taking the subresource, like `comments`, we're adding the full resource path, so we have `pulls_comments.rb`, `gists_comments.rb`, `issues_comments.rb`, etc. This also means other clients like `deployments.rb` and `hooks.rb` are now `repos_deployments.rb` and `repos_hooks.rb`.

Use full resource names for clients

---

.github/workflows/octokit.yml
Gemfile
spec/helper.rb

This PR fixes #1244 and removes the `coveralls` gem, since it's been throwing errors in our build and no longer seems to be maintained. We'll rely only on `simplecov` for our testing coverage.

Remove coveralls gem

---

lib/octokit/client/repositories.rb

Fixes link to REST API documentation for 'PATCH /repos/:owner/:repo'.
The link https://developer.github.com/v3/repos/#edit does not exist anymore.
Instead it is now https://developer.github.com/v3/repos/#update-a-repository.

Fixes docs link for 'PATCH /repos/:owner/:repo'

---

lib/octokit/client/organizations.rb

Fixes #1249. Updates the api paths in `organization.rb` to use `Organization.path(org)` instead of `org/{org_name}`. This allows organization id's to be used instead of organization names.

Update org paths to use Organization.path

---

.github/workflows/octokit.yml

Octokit doesn't have any OS specific functionality, so we don't need to run test suites against MacOS and Windows. 
This PR updates the workflow to only run on Ubuntu-latest.

Remove MacOS and Windows testing

---

lib/octokit/connection.rb
spec/octokit/client_spec.rb

This ensures adapters properly set SSL related options.
Adapters like Typhoeus [only check `options[:ssl][:verify]`](https://github.com/typhoeus/typhoeus/blob/v1.4.0/lib/typhoeus/adapters/faraday.rb#L137-L141).

Pass down ssl.verify to Faraday connection

---

lib/octokit/error.rb
lib/octokit/rate_limit.rb
spec/octokit/client_spec.rb

This adds the `context` attribute to `Octokit:: Error` for much smoother handling of exception like `Octokit::TooManyRequests` and `Octokit:: AbuseDetected`, so that clients consuming them can use the values specified for better retries. 
Can be consumed like this
```ruby
begin
octokit_client.get('resource')
rescue Octokit::TooManyRequests => rate_limited_error
puts "Retry in #{rate_limited_errro.retry_in} seconds"
end 
```
Specifically useful when using with background processors like `sidekiq`
```ruby
class PollingWorker
include Sidekiq::Worker
sidekiq_retry_in do |attempt, exception|
case exception
when Octokit::TooManyRequests
exception.context.resets_in
when Octokit::AbuseDetected
exception.context.resets_in
end
end
def perform
poller = Octokit::Client.new
data = …
```

Add context with rate limit struct for Octokit::TooManyRequests  and Octokit:: AbuseDetected errors

---

Rakefile

We've been reading in openapi definitions from `octokit/routes` but GitHub has started their own source of truth of openapi definitions. This PR uses these definitions instead.
Ideally, we'd probably want to switch this task to grab it from the internet, but as the definitions are still being worked on, I think this makes it easier to develop without introducing definition changes in the middle of random PRs.
But as this PR shows, this switch causes no difference to the generated files 🚀 
xref: #1157

Switch to GitHub's Openapi

---

CONTRIBUTING.md

It look like it probably preceded a link to the CoC in an earlier draft of 8e469aa11bf7f6fe8e9afb56998f8055572cc005, but now it's just dangling.

docs: Remove a dangling "Please abide by" from CONTRIBUTING.md [ci skip]

---

lib/octokit/error.rb
spec/octokit/client_spec.rb

rspec fails for Ruby head, but also did for current 4-stable branch:
https://github.com/stmllr/octokit.rb/runs/1093022877
What's the procedure to backport this PR to master? Is there anything I can do?

Add Octokit::InstallationSuspended error

---

lib/octokit/client/authorizations.rb

Alternative of https://github.com/octokit/octokit.rb/pull/1290
@tarebyte I changed the base branch and here's another one!

Fix typo: Techincally -> Technically [ci skip]

---

Gemfile

The json gem is a dependency for the test suite but we should still try to keep it up to date ✨

Update json gem for CVE-2020-10663

---

lib/octokit/client/apps.rb
lib/octokit/preview.rb
spec/octokit/client/apps_spec.rb

In August, Github "graduated" the Integrations API (aka [Apps API](https://docs.github.com/en/free-pro-team@latest/rest/reference/apps)) out of preview mode, into the official API - https://developer.github.com/changes/2020-08-20-graduate-machine-man-and-sailor-v-previews/. The `Accept: application/vnd.github.machine-man-preview+json` preview header is no longer required. Octokit still sets that header and it displays a warning if that header wasn't explcitly set by the user. 
This PR removes the `:integrations` preview header since it is no longer necessary. I didn't add any tests since there weren't any existing tests around preview headers.
Example `curl` request without the preview header (proving it's not necessary):
```
curl -H "Authorization: Bearer <token>" …
```

Remove integrations preview header

---

lib/octokit/client/organizations.rb

We were only returning the first page of results, even if the client `auto_paginate` option was set.

Paginate outside_collaborators calls

---

lib/octokit/response/feed_parser.rb
lib/octokit/response/raise_error.rb

Fixes https://github.com/octokit/octokit.rb/issues/1315
In https://github.com/lostisland/faraday/pull/1194 `on_complete` was introduced to `Faraday::Middleware` and was extracted out of `Faraday::Response`. Because our implementations of `on_complete` were `private` they no longer responded to `FaradayMiddleware#call`.
This updates all uses of `Octokit::Response::Middleware` so that `on_complete` isn't a private method.

Uses of FaradayMiddleware#on_complete should not be private

---

lib/octokit/error.rb
spec/octokit/client_spec.rb

When creating an app access token with `#create_app_installation_access_token`,
I received a response with the status `403`, which contains an error message like this:
```
POST https://api.github.com/app/installations/12345/access_tokens: 403 - This installation has been suspended // See: https://docs.github.com/rest/reference/apps#create-an-installation-access-token-for-an-app
```
I think this error should be raised as `Octokit::InstallationSuspended`.
What do you think?

Raise Octokit::InstallationSuspended when another error is received

---

lib/octokit/client/contents.rb

When you pass the ref option, you may not notice the syntax [here](https://github.com/octokit/octokit.rb/blob/8f95de13cb09cdbbf71e79d533ca52e009021554/README.md#additional-query-parameters). 
Therefore, it is convenient if this syntax is also described in RubyDoc.

Add documentation on how to specify the ref option for RubyDoc

---

lib/octokit/client/actions_workflow_runs.rb
spec/octokit/client/actions_workflow_runs_spec.rb

Changes add `delete_workflow_run` method to `Octokit::Client::ActionsWorkflowRuns` module.

Add delete_workflow_run method to Octokit::Client::ActionsWorkflowRuns module

---

lib/octokit/error.rb
spec/octokit/client_spec.rb

The error response with status `422` from GitHub includes an error message, `"Path diff too large"` when posting review comments on a "too large" file. I want to propose a new error class to handle this type of error.
```
$ octokit.create_pull_request_comment(245358625, 21, comment, d7a6bd842ee99bd3aafbf649b153391d43842b36, test.scss, 2)
Octokit::UnprocessableEntity: POST https://api.github.com/repositories/245358625/pulls/21/comments: 422 - Validation Failed
Error summary:
resource: PullRequestReviewComment
code: custom
field: path
message: path diff too large // See: https://docs.github.com/rest/reference/pulls#create-a-review-comment-for-a-pull-request
```

Add a new error: PathDiffTooLarge

---

lib/octokit/client/apps.rb
lib/octokit/client/checks.rb
lib/octokit/preview.rb
spec/octokit/client/apps_spec.rb
spec/octokit/client/checks_spec.rb

Remove "graduated" preview headers:
* Checks API's `antiope` preview header - see https://developer.github.com/changes/2020-10-01-graduate-antiope-preview/
* "Delete an installation" endpoint `gambit` preview header - https://developer.github.com/changes/2020-04-07-graduated-previews/
* "draft pull request " endpoint `shadow-cat` preview header

Remove "graduated" preview headers

---

lib/octokit/client/refs.rb
spec/octokit/client/refs_spec.rb

[/repos/{owner}/{repo}/git/refs](https://docs.github.com/en/rest/reference/git#create-a-reference) states
> Required. The name of the fully qualified reference (ie: refs/heads/master). **If it doesn't start with 'refs' and have at least two slashes**, it will be rejected.
Octokit tries to mask this complexity from the user: accepting `heads/foo` and prepending `refs/` instead of requiring `refs/heads/foo` be passed.
This misbehaved when `refs/` appears anywhere else in `ref`, like `heads/refs/is/slang/for/referees`. I've added a failing tests case and updated the regexp to only match against the start of input to fix it.

create_ref: match start of input

---

README.md

As of November 2020, the GitHub API does not allow you to authenticate to the API via username and password. See https://github.blog/changelog/2020-11-13-token-authentication-required-for-api-operations/ for more details.
Therefore login with user and password must be removed from the README file of the project.

Update README to remove Octokit client instance creation with username and password.

---

README.md

Reverts octokit/octokit.rb#1338
Although the username/password authentication has been deprecated, you can use the syntax as long as you [use your PAT](https://docs.github.com/en/rest/overview/other-authentication-methods#via-oauth-and-personal-access-tokens) instead of your password. Thus, these comments were valid so we can add them back ✨

Revert "Update README to remove Octokit client instance creation with username and password."

---

octokit.gemspec

Allow downstream projects to specify sawyer version

Updating Sawyer gem 

---

.github/workflows/octokit.yml

This PR extends the build matrix with the latest generally available Ruby version.

CI: Add 3.0 to matrix

---

spec/helper.rb

The ruby-head test suite is currently failing due to:
```
Failure/Error: require 'pry-byebug'
NameError:
undefined method `=~' for class `Pry::Code'
```
which was actually fixed in pry version 0.14.0, but unfortunately, pry-byebug’s latest version only allows for pry version 0.13.0 due to this unresolved issue: https://github.com/deivid-rodriguez/pry-byebug/issues/343
Since `pry-byebug` is only used locally and not in production systems, I think it's okay to remove it in versions of ruby >= 3.2 (which introduce the issue) to unblock the CI suites for now until pry-byebug begins supporting later versions of pry that incorporate the fix.

Fix `ruby-head` CI suite

---

lib/octokit/client.rb
lib/octokit/client/pub_sub_hubbub.rb
lib/octokit/connection.rb
lib/octokit/default.rb
lib/octokit/middleware/follow_redirects.rb
spec/octokit/client_spec.rb

Fix deprecation warning since Faraday 1.7.1

---

lib/octokit/client/organizations.rb

This PR updates the links to documentation about Organization Migrations. 
The old links resolve to https://docs.github.com/en/rest/reference/orgs#migrations, which doesn't exist. The proper link is https://docs.github.com/en/rest/reference/migrations#{{some link}}

Update broken links to Organization Migration documentation

---

README.md

This adds a section to the readme which explains when the library will raise exceptions and how you can work with them.
I did some work with `octokit/octokit.rb` and `octokit/octokit.js` recently, and I found that not having this meant that I had to do a bunch of digging myself to understand how I should handle unhappy paths.
As well as adding the error handling documentation, this PR also makes a few other small changes to the README: correcting, renaming and restructuring headings.

Document how and when the library raises exceptions

---

.github/workflows/octokit.yml

This PR adds Ruby 3.1 to the CI matrix.

Add Ruby 3.1 to CI

---

lib/octokit/enterprise_management_console_client/management_console.rb

@see
https://github.blog/changelog/2022-04-25-git-io-deprecation/

replace git.io link

---

README.md

Grammar issues are of most importance here. If anything needs updating, I would suggest those.

Fixes grammar and style

---

lib/octokit/client.rb
spec/octokit/client_spec.rb

This replaces @akerl original [PR](https://github.com/octokit/octokit.rb/pull/1117) due to heavy deviation of base branches and the age of the changeset.  The source change was pulled directly from his PR and a test was added to ensure the change.
From #1117 
> This should fix https://github.com/octokit/octokit.rb/issues/1113 . The issue there affected 2 of my gems as well. It looks like the fix for https://github.com/octokit/octokit.rb/issues/1088 accidentally affected nil values as well as false. Because nil is a common pattern for pass-through configuration, parameters set to nil should still be overridden by module defaults.

Ensures that any nil parameters being passed in will initalize with Octokit's defaults instead of nil

---

octokit.gemspec

This updates our gemspec to opt in to enforce multi-factor authentication (MFA) whenever we want to push releases of the gem, yank releases or add or remove owners.
This will increase the security of our users by making it more difficult for a bad actor to release a version of Octokit.rb.
After this is merged, the change will take effect from the first new release.
Fixes #1438.

Require multi-factor authentication to push new releases to RubyGems

---

lib/octokit/client/contents.rb

The `#create_contents` method currently has code, added for compatibility ruby Ruby 1.9.2, which uses different `Base64` methods depending on the Ruby version.
This removes that code, since we don't support 1.9.2 and the `.strict_encode64` method has been present since 1.9.3.
Fixes #1433.

Drop support for Ruby 1.9.2 in `Octokit::Client::Contents#create_contents`

---

RELEASE.md
script/package
script/release
script/validate

Adds details on how to check the files that are packed in the gem to help anyone who intends on releasing this make sure they are building and releasing this as intended.
This adds a script that is executed when the release or package scripts are run to naively check the permissions of the files in the gem - just as a safeguard.
Additionally, this adds parameters to script/release so that dry runs can be performed 
Hopefully, we'll be able to automate this, but for now, if anyone tries to release from something like a code space, for instance, then the gem will be released with world writeable files. We need to make sure that this is verified before release.

Adds details on how to run a manual file integrity check

---

lib/octokit/client.rb
lib/octokit/client/pub_sub_hubbub.rb
lib/octokit/connection.rb
spec/helper.rb
spec/octokit/client/actions_secrets_spec.rb
spec/octokit/client/actions_workflow_runs_spec.rb
spec/octokit/client/apps_spec.rb
spec/octokit/client/hooks_spec.rb
spec/octokit/client/organizations_spec.rb
spec/octokit/client/rate_limit_spec.rb
spec/octokit/client/releases_spec.rb
spec/octokit/client/repositories_spec.rb
spec/octokit/client/stats_spec.rb
spec/octokit/client_spec.rb
spec/octokit/enterprise_admin_client/search_indexing_spec.rb
spec/octokit/enterprise_admin_client/users_spec.rb
spec/octokit/enterprise_management_console_client/management_console_spec.rb

This PR fixes the following Ruby warnings by wrapping argument calls in parens:
```
.../lib/octokit/client.rb:255: warning: `*' interpreted as argument prefix
.../lib/octokit/connection.rb:110: warning: `*' interpreted as argument prefix
.../lib/octokit/connection.rb:116: warning: `*' interpreted as argument prefix
.../lib/octokit/client/pub_sub_hubbub.rb:94: warning: `*' interpreted as argument prefix
```
This PR also enables warnings in specs and fixes the following warnings reported when running specs:
```
warning: assigned but unused variable
```
```
WARNING: The preview version of the Template_repositories API is not yet suitable for production use.
You can avoid this message by supplying an appropriate media type in the 'Accept' request
header.
```

Suppress various warnings

---

.github/workflows/codeql-analysis.yml
.github/workflows/octokit.yml

Currently, the default branch for this repo is `4-stable` (not `main` or `master`) and we have some old code which was proposed to be the v5.x version of Octokit.rb in the `5-alpha` branch.
We now want to release a new major version of Octokit to drop support for old Ruby versions - see https://github.com/octokit/octokit.rb/pull/1424.
To do that, we'll delete the unused `master` branch and rename `4-stable` to `main`.
Ahead of that change, this updates our GitHub Actions workflows to support the name `main`. Once the rename is done, we can remove all of the references to the old branch names.

Trigger GitHub Actions workflows on the `main` branch

---

.github/workflows/codeql-analysis.yml
.github/workflows/octokit.yml

We've now renamed the `4-stable` branch to `main` and deleted the `master` branch (or, more accurately, renamed it to `master-old`).
This removes the references to those branches in our GitHub Actions workflow files.

Remove references to the `master` and `4-stable` branches in our Actions workflows

---

lib/octokit/client/pull_requests.rb
spec/octokit/client/pull_requests_spec.rb

Resolves #1471 
As per https://docs.github.com/en/rest/pulls/pulls#update-a-pull-request-branch. I couldn't get the specs to work with VCR despite creating a test repo and setting all relevant ENV vars. I decided to stub the request instead.

Adds ability to update pull request branch

---

lib/octokit/client/projects.rb

The current link 404s, I believe the docs were moved to https://docs.github.com/en/rest/projects

Update "See Also" link for projects API client

---

README.md

The subject is the message
The `faraday_http_cache` is currently in SourceLevel namespace (I'm the current maintainer) due to [Plataformatec acquires by Nubank](https://labsnews.com/en/news/business/nubank-acquires-consultancy-company-plataformatec/).

Fix `faraday_http_cache` link

---

RELEASE.md
script/release

This PR makes a number of improvements to our documentation and process for releasing a new version of the gem, contained in `RELEASE.md` and `script/release`. Specifically, it:
* fixes the instructions so you don't end up with two release commits - one created manually by following the instructions, and one created by `script/release`
* updates `script/release` to use the version number of the latest version when generating the commit message and Git tag, not the _oldest_ version (this is fine if you only have one `.gem` file, but not if you have old ones hanging around!)
* tweaks the commit message from the release script to be a simpler `v1.2.3` not `Release 1.2.3`

Tweak release documentation and process

---

lib/octokit/client.rb
lib/octokit/client/actions_artifacts.rb
spec/cassettes/Octokit_Client_ActionsArtifacts/_artifact/returns_the_requested_artifact.json
spec/cassettes/Octokit_Client_ActionsArtifacts/_artifact_download_url/returns_the_location_of_artifact_zip_archive.json
spec/cassettes/Octokit_Client_ActionsArtifacts/_delete_artifact/deletes_the_artifact.json
spec/cassettes/Octokit_Client_ActionsArtifacts/_repository_artifacts/returns_all_artifacts_for_a_repository.json
spec/cassettes/Octokit_Client_ActionsArtifacts/_workflow_run_artifacts/returns_all_artifacts_for_a_workflow_run.json
spec/octokit/client/actions_artifacts_spec.rb

Partially addresses https://github.com/octokit/octokit.rb/issues/1216.
This adds support for the Actions artifact APIs documented at https://docs.github.com/en/rest/actions/artifacts.

Add client methods to support Actions artifact APIs.

---

lib/octokit/client/actions_artifacts.rb

With each client method, we include its URL in our API documentation on https://docs.github.com. After releasing v5.6.0, I spotted that the URL for `#artifact_download_url` was incorrect, pointing to a different API. This fixes it.

Correct documentation URL for `#artifact_download_url`

---

lib/octokit/client/hooks.rb
spec/octokit/client/hooks_spec.rb

Fixes #1430. 
As noted by Tim in the above issue, this should land in a breaking change even though the underlying API hasn't been operational for some time.

Remove Octokit::Client::Hooks#available_hooks

---

lib/octokit/version.rb

As a result of #1494 and #1495, we're cutting a new major release (even though the APIs that underly this functionality has long been deprecated).

Bump to v6.0.0

---

Gemfile

Resolves #1519. Thank you @composerinteralia for the tip!
Previously, our Ruby head build was failing looking for a specific version of json in a list of empty platforms. Speculative: perhaps an underlying change in Ruby or bundler caused errors with the `platforms: [:jruby]` specification in our Gemfile.
----
* Ruby head builds are broken due to a gem resolution error. 
* Ruby head builds are successful.
* This issue is obnoxious! We want to fix the build so we can ship several PRs we have on deck. 
----
* N/A
- Feature/model/API additions: …

Remove jruby-specific platform

---

lib/octokit/client/repositories.rb
spec/cassettes/Octokit_Client_Repositories/_branches/returns_a_single_branch_that_includes_character_that_needs_to_be_escaped.json
spec/octokit/client/repositories_spec.rb

Resolves #1250
----
If a fragment identifier (#) is part of the name of the branch, Repository#branch will return 404 if it doesn't escape the identifier.
* Accessing a branch of name `#1234-my-test` would not return the branch
* Accessing a branch of name `#1234-my-test` will return the proper branch
* The specs will fail I believe until we have a branch that reflects the test since it will require a VCR entry.
----
* If customer of this library were already escaping the branch name, it will result in a double escape issue and the branch won't be found.
- Bugfix: …

Repository: Fix issue with fragment identifier in branch name

---

.rubocop.yml

Fix the following rubocop warning.
> Warning: obsolete parameter `IgnoredMethods` (for `Metrics/BlockLength`) found in .rubocop.yml
`IgnoredMethods` has been renamed to `AllowedMethods` and/or `AllowedPatterns`.

Rename obsolete parameter `IgnoredMethods` to `AllowedMethods`

---

lib/octokit/rate_limit.rb
spec/octokit/client_spec.rb
spec/octokit/rate_limit_spec.rb

Resolves #1400 
----
* `Octokit::TooManyRequests#context.rate_limit` methods return nil
* `Octokit::TooManyRequests#context.rate_limit` methods return the correct values
* I've left this as prioritizing the `headers` field over `response_headers`, it's not clear to me when `headers` was valid (I'm not sure if it was an older version of faraday or something), I looked through the code and I think it's because the `on_complete` uses `response_env` (might be [here](https://github.com/octokit/octokit.rb/blob/82765ce829c109644d520d11e86f8673203eb83f/lib/octokit/middleware/follow_redirects.rb#L75) instead of `response` (`Faraday::Response` has `headers` delegating to `env.response_headers`
Note: I can't see where to add in bug fix information in this repo?
----
Please see our docs on [breaking …

Allow using the response_headers or headers when getting Rate Limit Info

---

README.md

* Ruby 3.2 is missing for tested implementations in the README.md.
* Add Ruby 3.2 to the tested implementations in the README.md.
This PR is follow up https://github.com/octokit/octokit.rb/pull/1524.
----
* N/A
----

Add Ruby 3.2 to tested implementations in README

---

.rubocop.yml
.rubocop_todo.yml
Rakefile
lib/octokit/client.rb
lib/octokit/configurable.rb
lib/octokit/default.rb
lib/octokit/gist.rb
lib/octokit/repository.rb
spec/octokit/client/actions_secrets_spec.rb
spec/octokit/client/deployments_spec.rb
spec/octokit/client/hooks_spec.rb
spec/octokit/client/issues_spec.rb
spec/octokit/client/reactions_spec.rb
spec/octokit/client/refs_spec.rb
spec/octokit/client/repositories_spec.rb
spec/octokit/client/repository_invitations_spec.rb
spec/octokit/client/source_import_spec.rb

Version mismatch between `required_ruby_version` of gemspec and `TargetRubyVersion` of .rubocop.yml. Therefore, some new syntax up to Ruby 2.7 is not used.
gemspec `required_ruby_version` requires 2.7 and higher, so specify `TargetRubyVersion` to 2.7. Some syntax detected by updating to 2.7 applies.
It also removes `Gemspec/RequiredRubyVersion` cop from .rubocop_todo.yml to enable the cop so that version mismatch can be detected.
This PR is follow up https://github.com/octokit/octokit.rb/pull/1454.
----
* N/A
- Feature/model/API additions: …

Specify `TargetRubyVersion: 2.7` in .rubocop.yml

---

README.md
lib/octokit/default.rb

Resolves #1188 
----
* Octokit would not retry on timeouts
* Octokit does retry on timeouts
* It's pretty straightforward, I can see the original issue marks this as a breaking change.
----
* This _could_ be a breaking change since Octokit will now retry on errors it didn't before, but https://github.com/octokit/octokit.rb/pull/1021 wasn't marked as a breaking change,
I want to mark this as a bug, but I can understand if it's a feature!

Add Faraday DEFAULT_EXCEPTIONS for when retry middleware is available

---

lib/octokit/client/organizations.rb
spec/cassettes/Octokit_Client_Organizations/_delete_organization/deletes_an_organization.json
spec/octokit/client/organizations_spec.rb

This PR adds `Octokit::Client#delete_organization` for the recently added API endpoint to delete an org:
https://docs.github.com/rest/orgs/orgs#delete-an-organization
Resolves https://github.com/octokit/octokit.rb/issues/1557
----
* The Octokit client could not delete orgs.
* The Octokit client can delete orgs.
* Changelog item: Add `Octokit::Client#delete_organization` for new API endpoint to delete organizations.
----
* N/A
(I can't add labels)
----

Add `Octokit::Client#delete_organization` to support org deletion

---

lib/octokit/client.rb
lib/octokit/client/environments.rb
spec/cassettes/Octokit_Client_Environments/_create_or_update_environment/when_creating/with_options/creates_an_environment.json
spec/cassettes/Octokit_Client_Environments/_create_or_update_environment/when_creating/without_options/creates_an_environment.json
spec/cassettes/Octokit_Client_Environments/_create_or_update_environment/when_updating/updates_the_environment.json
spec/cassettes/Octokit_Client_Environments/_delete_environment/deletes_the_environment.json
spec/cassettes/Octokit_Client_Environments/_environment/returns_the_environment.json
spec/cassettes/Octokit_Client_Environments/_environments/lists_environments.json
spec/octokit/client/environments_spec.rb

Resolves #1552
----
* Environments API did not exist (https://docs.github.com/en/rest/deployments/environments)
* Environments API is implemented
* 
----
* N/A
----

Added Environments API

---

lib/octokit/error.rb
spec/octokit/error_spec.rb

Resolves #1559
----
* Prior to the change, the api_token that was passed via URI (currently the only way the GitHub REST API accepts this value) was being persisted and sent to STDOUT in the stack trace when errors occurred.
* The value of the key from the URL now displays as `http://127.0.0.1:8989/setup/api/settings?api_key=(redacted)`
I added tests for the private method.
I have mixed feelings about testing this method from this class like this due to potentially breaking encapsulation, but given the nature of this method and the fact that it is meant to keep secrets out of logs.
I feel like it is worth it and will help us know if something changes in this area.
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) …

[bugfix] Ensures that he API Token in clear text is never present in the error stack trace when set in the URL

---

.github/workflows/octokit.yml
Gemfile
Rakefile

This PR makes developer tests parallel using test-queue: https://github.com/tmm1/test-queue
Around 55 seconds:
```console
$ bundle exec rake spec
(snip)
Finished in 55.03 seconds (files took 0.77671 seconds to load)
865 examples, 0 failures
Randomized with seed 6253
```
Around 11 seconds (e.g. 8 CPUs with hyper threading) :
```console
$ bundle exec rake spec
rspec-queue spec
Starting test-queue master (/tmp/test_queue_12223_3620.sock)
==> Summary (16 workers in 11.6051s)
[ 1]                                      65 examples, 0 failures         1 suites in 7.1969s      (pid 12226 exit 0 )
[ 2]                                      19 examples, 0 failures         1 suites in 7.3070s      (pid 12227 exit 0 )
[ 3]                                      20 examples, 0 failures         1 suites in …
```

Use test-queue for parallel testing

---

lib/octokit/client/pull_requests.rb

[To rename the 'position' argument of create_pull_request_comment to 'line' and mark it as deprecated in advance.](https://github.com/octokit/octokit.rb/pull/1566#issuecomment-1547334434)
----
* Add comment for deprecation on create_pull_request_comment.
* In the next major version, [this PR](https://github.com/octokit/octokit.rb/pull/1566) will be released.
----
* N/A
----

Add comment for deprecation on create_pull_request_comment.

---

lib/octokit/client/organizations.rb

Fix a small typo in a comment in `lib/octokit/client/organizations.rb`.
----

Fix typo in `organizations.rb`

---

lib/octokit/version.rb

Since #1596 has been merged, we should cut a new major release version. Once this change is merged, I'll follow the instructions [here](https://github.com/octokit/octokit.rb/blob/main/RELEASE.md) to create a new RubyGems release.

Bump major versions to v7.0.0

---

lib/octokit/client/actions_secrets.rb
spec/cassettes/Octokit_Client_ActionsSecrets/with_a_repository_environment_with_a_secret/_create_or_update_actions_environment_secret/updating_existing_secret_returns_204.json
spec/cassettes/Octokit_Client_ActionsSecrets/with_a_repository_environment_with_a_secret/_delete_actions_environment_secret/delete_existing_secret.json
spec/cassettes/Octokit_Client_ActionsSecrets/with_a_repository_environment_with_a_secret/_get_actions_environment_secret/return_timestamps_related_to_one_secret.json
spec/cassettes/Octokit_Client_ActionsSecrets/with_a_repository_environment_with_a_secret/_list_actions_environment_secrets/auto-paginates_the_results.json
spec/cassettes/Octokit_Client_ActionsSecrets/with_a_repository_environment_with_a_secret/_list_actions_environment_secrets/paginates_the_results.json
spec/cassettes/Octokit_Client_ActionsSecrets/with_a_repository_environment_with_a_secret/_list_actions_environment_secrets/returns_list_of_two_secrets.json
spec/cassettes/Octokit_Client_ActionsSecrets/with_an_environment_without_a_secret/_create_or_update_actions_environment_secret/creating_secret_returns_201.json
spec/cassettes/Octokit_Client_ActionsSecrets/with_an_environment_without_a_secret/_get_actions_environment_public_key/get_environment_specific_public_key_for_secrets_encryption.json
spec/cassettes/Octokit_Client_ActionsSecrets/with_an_environment_without_a_secret/_list_actions_environment_secrets/returns_empty_list_of_secrets.json
spec/octokit/client/actions_secrets_spec.rb

Resolves https://github.com/octokit/octokit.rb/issues/1611
----
* Endpoints for environment secrets within Actions were not supported.
* All of the `actions_secret` methods have been mapped to equivalents that support `environments`.
* `get_actions_environment_public_key` 
* `list_actions_environment_secrets`
* `get_actions_environment_secret`
* `create_or_update_actions_environment_secret`
* `delete_actions_environment_secret` 
No breaking changes here!
----

Add support for Actions Environment Secret Management

---

lib/octokit/client/apps.rb
spec/cassettes/Octokit_Client_Apps/_deliver_app_hook/schedules_a_webhook_for_redelivery.json
spec/cassettes/Octokit_Client_Apps/_list_app_hook_deliveries/allows_auto_pagination.json
spec/cassettes/Octokit_Client_Apps/_list_app_hook_deliveries/lists_hook_deliveries_for_an_app.json
spec/cassettes/Octokit_Client_Apps/with_app_installation/_list_app_hook_deliveries/lists_hook_deliveries_for_an_app.json
spec/octokit/client/apps_spec.rb

Resolves #1619
----
* The endpoints for /app/hooks are not yet implemented
* Implementations for listing app webhooks and retriggering delivery have been implemented
This is my first PR to Octokit and I wasn't able to get a test working using the JWT token, would appreciate some pointers here!
----

[feat]: add methods for app hook deliveries

---

lib/octokit/client/reactions.rb
spec/cassettes/Octokit_Client_Reactions/with_repository/with_release/_create_release_reaction/creates_a_reaction.json
spec/cassettes/Octokit_Client_Reactions/with_repository/with_release/_delete_release_reaction/deletes_the_reaction.json
spec/cassettes/Octokit_Client_Reactions/with_repository/with_release/_release_reactions/returns_an_Array_of_reactions.json
spec/octokit/client/reactions_spec.rb

Resolves #1633
----
* There were no endpoints to get a release's reactions, create a release reaction or delete a release reaction
* I added those endpoints to the `Client::Reactions` module
----
I'm having an issue trying to run the tests I've written.
I've exported a `OCTOKIT_TEST_GITHUB_TOKEN` with a new token I've created before forking the app (the token has all the rights I could give it) but despite doing that I get a `Octokit::Unauthorized: POST https://api.github.com/user/repos: 401 - Bad credentials` error.
I've tried another token that I use in my personal repos and it fails too so I don't think the issue comes from the tokens but probably from …

Add missing endpoints to Reactions

---

README.md

These should've come out in 017b0e3bc4aafed817142db3765d02e88d926228.
Resolves #1639
----
* The docs refer to a method that no longer exists.
* The docs won't refer to the missing method, though this adds no documentation to describe what replaced it, if anything.
----

Drop refs to `create_authorization` from README

---

lib/octokit/client/oauth_applications.rb

Documentation for method name in oauth_applications.rb is wrong [here ](https://github.com/octokit/octokit.rb/blob/dcbfa148ea1b41d83aac7bd4a39265ef90aab417/lib/octokit/client/oauth_applications.rb#L68) fixed it.

Fix documentation for oauth_applications [ci skip]

---

lib/octokit/client/users.rb
spec/fixtures/renew_access_token.json
spec/octokit/client/users_spec.rb

Resolves #I1652
----
* Missing functionality to renew an access token when github app is authenticated.
* Expired access tokens can be renewed using refresh access token.
* Method added in **lib/octokit/client/users.rb**
----

feat: Renew access token with refresh access token

---

lib/octokit/client/deployments.rb

* It was not possible to paginate automatically this two endpoints.
* It is possible to paginate the result for `deployments` and `deployment_statuses`.
I followed https://github.com/octokit/octokit.rb/pull/1032/files and doesn't seems it is required here?

Paginate deployments

---

octokit.gemspec

octokit.rb warns the following message With Ruby 3.3.0.
```
/Users/hsbt/.local/share/gem/gems/octokit-8.0.0/lib/octokit/client/code_scanning.rb:3: warning: base64 was loaded from the standard library, but is not part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of octokit-8.0.0 to add base64 into its gemspec.
```
This means octokit.rb is not working after Ruby 3.4 release. We should add `base64` as dependency.
Above warning is suppressed.
----

maint: Added base64 gem explicitly dependency

---

Gemfile
lib/octokit/client/code_scanning.rb
lib/octokit/client/contents.rb
octokit.gemspec
spec/octokit/client/licenses_spec.rb

#1658 added base64 as a dependency in order to supress a warning/error on Ruby 3.3/3.4.
There are two places here where it is used, and these can instead be replaced by the `pack` method which the base64 gem just wraps around.
I've instead added it as a development dependency so that tests can continue to make use of it.
Other gems have taken a similar approach:
* https://github.com/rubocop/rubocop/pull/12313
* https://github.com/rack/rack/pull/2110
* https://github.com/elastic/elasticsearch-ruby/pull/2295
* https://github.com/socketry/protocol-http/pull/51
* etc.
----
`base64` is part of the depenency tree.
`base64` is removed.
----

Drop runtime dependency on base64

---

lib/octokit/client/apps.rb
spec/cassettes/Octokit_Client_Apps/_app_hook_delivery/returns_a_webhook_delivery.json
spec/octokit/client/apps_spec.rb

- Added a new `app_hook_delivery` to retrieve one webhook delivery for an app.
Ref https://docs.github.com/en/rest/apps/webhooks#get-a-delivery-for-an-app-webhook
----
No method is implemented to get a specific webhook delivery for an app. 
User can now call `client.app_hook_delivery('delivery-123')` to get the webhook delivery resource.
----

Add method to get a webhook delivery:

---

lib/octokit/client/environments.rb

* Listing environments would only fetch the first page if `auto_paginate` is set to `true`.
* Listing environments will fetch all the pages if `auto_paginate` is set to `true`.
No

fix: Use auto pagination when retrieving environments

---

README.md

The current release is v8 so this was very out of date. I think it's better just to remove than to keep updating.

Remove outdated version constraint from README

---

lib/octokit/enterprise_management_console_client/management_console.rb

* Management Console API deprecation version was 3.14
* Management Console API deprecation version is 3.15
----

Management Console Client: Update deprecation version

---

lib/octokit/repository.rb

But also older Rubies if the default URI parser is set to `RFC3986`.

fix: Addresses URI parsing compatibility with Ruby 3.4

---

lib/octokit/client/repositories.rb
spec/cassettes/Octokit_Client_Repositories/_automated_security_fixes_enabled_/returns_false_with_automated_security_fixes_disabled.json
spec/cassettes/Octokit_Client_Repositories/_automated_security_fixes_enabled_/returns_true_when_automated_security_fixes_are_enabled.json
spec/cassettes/Octokit_Client_Repositories/_disable_automated_security_fixes/disables_automated_security_fixes_for_the_repository.json
spec/cassettes/Octokit_Client_Repositories/_enable_automated_security_fixes/enables_automated_security_fixes_for_the_repository.json
spec/octokit/client/repositories_spec.rb

Resolves #1704
----
* N/A
* Enable, disable and check status of automated security fixes
----

feat: enable and disable automated security features

---

lib/octokit/default.rb
lib/octokit/enterprise_management_console_client/management_console.rb
lib/octokit/manage_ghes_client/manage_ghes.rb
spec/octokit/enterprise_management_console_client/management_console_spec.rb
spec/octokit/ghes_manage_client/ghes_manage_spec.rb

Resolves #1701
----
* A warning message related to the Faraday Multipart middleware is always printed at boot time.
At runtime, a Faraday error is raised and the message of what happened is not clear.
* The warning message is not printed at boot time. A better error and message is raised at runtime.
----

fix: Remove the Faraday multipart warning and tweak the error message raised at runtime when Faraday Multipart is not installed

---

lib/octokit/client/pull_requests.rb
spec/cassettes/Octokit_Client_PullRequests/methods_that_require_a_new_pull/methods_requiring_a_pull_request_comment/_create_pull_request_comment/without_line_argument/creates_a_new_comment_on_a_pull_request_at_the_file_level.json
spec/octokit/client/pull_requests_spec.rb

Resolves #1710
----
* Even if you provided a `nil` line when creating a pull request comment, with the intention of commenting the whole file, you would get an answer like
```
{
"message": "Invalid request.\n\nNo subschema in \"oneOf\" matched.\n\"position\" wasn't supplied.\n\"in_reply_to\" wasn't supplied.\n\"subject_type\" is not a permitted key.\nFor 'properties/line', nil is not an integer.\n\"line\" is not a permitted key.",
"documentation_url": "https://docs.github.com/rest/pulls/comments#create-a-review-comment-for-a-pull-request",
"status": "422"
}
```
Per [GitHub documentation](https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28):
> line integer
Required unless using subject_type:file. ...
* If you don't provide a `line`, the `file` subject type will be used, …

Add support for file comments in PRs

---

README.md

Update the sample code for enabling HTTP debugging in Faraday to work with newer versions of Faraday.
----
* In testing using ruby 3.2.3, faraday 2.12.0 and faraday-retry 2.2.1, I found that the included sample code failed with this error:
```
uninitialized constant Faraday::Retry (NameError)
builder.use Faraday::Retry::Middleware, exceptions: Faraday::Request::Retry::DEFAULT_EXCEPTIONS + [Octokit::ServerError] # or Faraday::Request::Retry for Faraday < 2.0
^^^^^^^^^^^^
from /Users/$USER/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/faraday-2.12.0/lib/faraday/rack_builder.rb:74:in `build'
from /Users/$USER/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/faraday-2.12.0/lib/faraday/rack_builder.rb:63:in `initialize'
```
* After making the proposed to point to this constant: …

Update the "debugging" sample code in `README.md`

---

lib/octokit/client/reactions.rb
spec/cassettes/Octokit_Client_Reactions/with_repository/with_issue/with_issue_comment/_delete_issue_comment_reaction/deletes_the_reaction.json
spec/octokit/client/reactions_spec.rb

----
* Octokit.rb was missing the `delete_issue_comment_reaction()` method.
* This method has been implemented so that users can call `.delete_issue_comment_reaction()` to delete a reaction from a given issue comment.
----
I used the documentation found [here](https://github.com/octokit/plugin-rest-endpoint-methods.js/blob/bf6cc4c0237abd467c1a6125f675db1ea4f7eaab/docs/reactions/deleteForIssueComment.md) to construct this method.
---
related: https://github.com/octokit/octokit.rb/pull/1637

feat: add missing method `delete_issue_comment_reaction()`

---

lib/octokit/error.rb
spec/octokit/client_spec.rb

Just came across this in the wild
https://github.com/openSUSE/open-build-service/issues/17535
Apparently sometimes the validation json is formated like that.
----
* `Octokit::Error.response_error_summary` crashes
* `Octokit::Error.response_error_summary` succeeds 
----

Fix string validation errors
