octokit/octokit.rb

spec/octokit/client/organizations_spec.rb

Fixes test failures due to inconsistency between test cassette and spec.

Update org spec to use ENV defined github login

---

lib/octokit/client.rb

Stop appending headers to querystring

---

lib/octokit/client/issues.rb
lib/octokit/repository.rb
spec/octokit/repository_spec.rb

Handle invalid argument types passed to Repository

---

README.md

…unless you think it's not ready for prime time yet. ;-)

Suggest installing the newly-released 4.x gem

---

lib/octokit/client/stats.rb

Apologies if I didn't follow the process correctly.

updated link in docs for client::commit_activity_stats

---

lib/octokit/client/authorizations.rb

Closes #643, this allows the user to pass additional options to the `scopes` method.
Feedback welcome
/cc @johndbritton @pengwynn

Merge authorization header with options

---

CONTRIBUTING.md

Update about branching link

---

.travis.yml

Configure emails to be turned off

Turn off email notifications

---

lib/octokit/client/issues.rb

Hi,
I just got bit by this. Both my observations and the official API doc agrees on it: https://developer.github.com/v3/issues/#create-an-issue
Regards

Outdated documentation: Labels must be an array

---

lib/octokit/client/hooks.rb
lib/octokit/client/licenses.rb
lib/octokit/client/organizations.rb
lib/octokit/client/pull_requests.rb
lib/octokit/client/releases.rb
lib/octokit/client/repositories.rb
lib/octokit/client/stats.rb

Fix a number of documentation urls

Fix documentation urls

---

README.md

Clarify config defaults behaviour

---

lib/octokit/client/stats.rb
spec/octokit/client/stats_spec.rb

Riffing on #687, this takes a test-driven approach to adding a retry option to fetching stats.
Merry Christmas @kv109 :gift: :christmas_tree: https://github.com/octokit/octokit.rb/pull/687#issuecomment-167116234
/cc @joeyw for :eyes: 
Closes #685, closes #687

Fetch stats with retry

---

README.md

Add simple example how to pass query params to `get` method.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/octokit/octokit.rb/717)

Update README with query example

---

README.md

Add a table of contents to our massive readme file

Add Table of Contents to Readme [ci skip]

---

lib/octokit/repository.rb
spec/octokit/repository_spec.rb

Parse repositories from api urls in Repository.from_url method /cc @pengwynn @aroben #704

Support API urls in Repository.from_url method #704

---

lib/octokit/client/repository_invitations.rb

Fix .decline_repository_invitation API doc url [ci skip]

Fix .decline_repository_invitation API doc url [ci skip]

---

README.md

Perhaps an automation went wrong? In any case, this brings it back.

Fix Gundam in the README

---

lib/octokit/client/gists.rb
lib/octokit/client/statuses.rb
lib/octokit/client/users.rb

Fixes #813
I had originally opened PR #780, which is mentioned in #813, and
thought I would take a look through the repo for other places where mutating
opts args could be avoided.

Change several occurrences of `Hash#merge!`

---

lib/octokit/client/reviews.rb

Per <https://developer.github.com/v3/pulls/reviews/> and <https://developer.github.com/v3/pulls/review_requests/>, these routes can be paginated.

Allows reviews and review comments to be paginated

---

README.md

Update per_page documentation.

---

README.md

Update documentation on additional query parameters.

---

lib/octokit/client/reviews.rb

👋  Stumble across a small url mistake on the pull review api url
Thanks for this great gem!

Url to the review API was wrong

---

README.md

Sorry for the branch name — I edited this in the GitHub GUI. Let me know if you want me to open a new PR with a better branch name.

Fixes small mistake in README

---

lib/octokit/preview.rb

https://developer.github.com/changes/2018-09-26-pass-header-to-test-strict-validation-in-rest-api/

Add new strict validation preview header

---

lib/octokit/client/repositories.rb

#434 ensured the predicate method to return a boolean but forgot to update the return tag.

Fix docs of #repository? return value type

---

lib/octokit/preview.rb

As mentioned in https://developer.github.com/changes/2019-02-14-draft-pull-requests/

Add drafts preview accept header

---

lib/octokit/error.rb
spec/octokit/client_spec.rb

Useful for integrators of Marketplace apps

Add BillingIssue error

---

lib/octokit/client/pull_requests.rb

- pull_request state option has all options :) 
ref: https://developer.github.com/v3/pulls/#parameters

update pull_requests.rb document

---

lib/octokit/client/issues.rb

most of assign user method have some user assign method.
I checked between api document and octokit document, so i update octokit document. 
https://developer.github.com/v3/issues/#create-an-issue

update assignee document

---

lib/octokit/client/apps.rb

Hi, I found some incorrect URLs for Apps API. This fixes only URLs in RDoc.

Fix incorrect API URLs for Apps

---

.github/workflows/octokit.yml

This PR reverts part of #1263. We removed the workflow from running on pull requests, which we actually still want 😅

Run actions on pull requests

---

lib/octokit/client/oauth_applications.rb

These were errors from yard when I was generating the new docs.

Fix OauthApplication documentation issues

---

lib/octokit/client/actions_workflows.rb
spec/octokit/client/actions_workflows_spec.rb

This adds support for https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event

Add support for workflow_dispatch

---

README.md

To avoid naively copying/pasting the example code and ending up with token in clear in logs. 😬

Improve debugging logger example code in README

---

.rubocop_todo.yml
lib/octokit/client.rb
lib/octokit/client/actions_workflow_jobs.rb
lib/octokit/client/actions_workflow_runs.rb
spec/octokit/client/actions_workflow_jobs_spec.rb

- Add support for https://docs.github.com/en/rest/actions/workflow-jobs
- Add missing workflow run documentation

Add support for Actions Workflow jobs API

---

lib/octokit/client/actions_workflow_runs.rb
spec/octokit/client/actions_workflow_runs_spec.rb

Add support for workflow run usage: https://docs.github.com/en/rest/actions/workflow-runs#get-workflow-run-usage

Add support for `workflow_run_usage`

---

README.md

* There was no explanation in the README for authentication using GitHub App.
* Add using GitHub app authentication for README.
Reference information.
* [Authenticating with GitHub Apps](https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps)
----
----

Add using GitHub app authentication in README

---

lib/octokit/client/search.rb

I figured that this could be a good addition as It puzzled me for a while

[docs] Add link to search limits

---

lib/octokit/client/reviews.rb

Resolves #ISSUE_NUMBER
https://github.com/octokit/octokit.rb/issues/1597
"See also" section of [request pull request review page](http://octokit.github.io/octokit.rb/Octokit/Client/Reviews.html#request_pull_request_review-instance_method) links to https://developer.github.com/v3/pulls/review_requests/#create-a-review-request, which doesn't exist.
"See also" section of [request pull request review page](http://octokit.github.io/octokit.rb/Octokit/Client/Reviews.html#request_pull_request_review-instance_method) links to https://developer.github.com/v3/pulls/review_requests/#request-reviewers-for-a-pull-request, which exists.
----

update broken link

---

lib/octokit/version.rb

The purpose here is to release the Actions Environment secrets introduced by @hosom in #1607.

Update version to v7.1.0

---

lib/octokit/version.rb

With #1566 in, it's time to bump the major version and create a new release!

Bump version to v8
